server:
  port: 8803

spring:
  application:
    name: cloud-stream-consumer
  #位置要对齐！
  cloud:
    stream:
      binders:    #此处配置要绑定的RabbitMQ的服务包
        defaultRabbit:  #表示定义的名称，用于binding整合
          type: rabbit  #消息组件类型
          environment:  #设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest

      bindings: #服务的整合处理
        input: #这个名字是一个通道的名字
          destination: studyExchange  #表示要使用的Exchange名称定义
          content-type: application/json  #设置消息类型，本次为json，文本则设置“text/plain”
         binder: defaultRabbit                        #设置要绑定的消息服务的具体设置
         # group: oykB   #自定义分组，若分组名相同则竞争消费  若分组名不相同则重复消费  以及数据持久化
          group: oykA   #自定义分组，若分组名相同则竞争消费  若分组名不相同则重复消费  以及数据持久化


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true.单节点无所谓。集群必须设置为true才能配合Ribbon使用负责均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka 单机版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
      defaultZone: http://eureka7001.com:7001/eureka/

  instance:
    instance-id: receive-8803.com     #主机名：服务名称修改
    prefer-ip-address: true     #访问路径可以显示IP地址